package pojo;

import java.util.List;

import dal.annotations.Column;
import dal.annotations.DBCollection;
import dal.annotations.Storeable;

@Storeable(tableName = "Functions")
public class Function {
	@Column(autoGenerated = true, pk = true, columnName = "id")
	private long id;
	
	@Column(columnName = "name")
	private String name;
	
	@Column(columnName = "description")
	private String description;
	
	@DBCollection(klass = User.class, thisPk = {"id"}, fk = {"functionID"})
	private List<User> usersWithThatFunction;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<User> getUsersWithThatFunction() {
		return usersWithThatFunction;
	}
}
