package pojo;

import java.util.Arrays;

import dal.annotations.Column;
import dal.annotations.Storeable;

@Storeable(tableName = "Resources, PlaceResources")
public class PlaceResource extends Resource {
	@Column(columnName = "PlaceResources.resourceID", pk = true, autoGenerated = true)
	public long resourceID;
	
	@Column(columnName = "PlaceResources.code")
	public String code;
	
	@Column(columnName = "PlaceResources.length")
	public int length;
	
	@Column(columnName = "PlaceResources.width")
	public int width;
	
	@Column(columnName = "PlaceResources.capacity")
	public int capacity;

	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public int getLength() {
		return length;
	}
	public void setLength(int length) {
		this.length = length;
	}
	public int getWidth() {
		return width;
	}
	public void setWidth(int width) {
		this.width = width;
	}
	public int getCapacity() {
		return capacity;
	}
	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}
	
	public static void main(String[] args) {
		System.out.println(Arrays.toString(PlaceResource.class.getFields()));
	}
}
