package pojo;

import java.sql.Timestamp;
import java.util.List;

import dal.annotations.Column;
import dal.annotations.ForeignKey;
import dal.annotations.ManyToMany;
import dal.annotations.Storeable;

@Storeable(tableName = "Reservations")
public class Reservation {
	
	@Column(columnName = "id", autoGenerated = true, pk = true)
	public long id;
	
	@Column(columnName = "solicitationTime")
	public Timestamp solicitationTime;
	
	@Column(columnName = "beginTime")
	public Timestamp beginTime;
	
	@Column(columnName = "endTime")
	public Timestamp endTime;
	
	@Column(columnName = "approved")
	public boolean approved;
	
	@Column(columnName = "pendingApproval")
	public boolean pendingApproval;
	
	@Column(columnName = "userCpf")
	public String userCpf;
	@ForeignKey(thisSideAttrs = {"userCpf"}, otherSideAttrs = {"cpf"})
	public User user;
	
	@Column(columnName = "placeID")
	public long placeID;
	@ForeignKey(thisSideAttrs = {"placeID"}, otherSideAttrs = {"id"})
	public PlaceResource placeReserved;
	
	@ManyToMany(onTable = "Reservations_Objects", otherClass = ObjectResource.class,
		thisPK = {"id"}, thisPKOtherSide = {"reservationID"}, otherPK = {"id"}, otherPKOtherSide = {"objectID"})
	public List<ObjectResource> objects;
	
	public List<ObjectResource> getObjects() {
		return objects;
	}
	public void setObjects(List<ObjectResource> objects) {
		this.objects = objects;
	}
	public boolean isPendingApproval() {
		return pendingApproval;
	}
	public void setPendingApproval(boolean pendingApproval) {
		this.pendingApproval = pendingApproval;
	}
	public long getPlaceID() {
		return placeID;
	}
	public void setPlaceID(long placeID) {
		this.placeID = placeID;
	}
	public PlaceResource getPlaceReserved() {
		return placeReserved;
	}
	public void setPlaceReserved(PlaceResource placeReserved) {
		this.placeReserved = placeReserved;
	}
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public Timestamp getSolicitationTime() {
		return solicitationTime;
	}
	public void setSolicitationTime(Timestamp solicitationTime) {
		this.solicitationTime = solicitationTime;
	}
	public Timestamp getBeginTime() {
		return beginTime;
	}
	public void setBeginTime(Timestamp beginTime) {
		this.beginTime = beginTime;
	}
	public Timestamp getEndTime() {
		return endTime;
	}
	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}
	public boolean isApproved() {
		return approved;
	}
	public void setApproved(boolean approved) {
		this.approved = approved;
	}
	public boolean isPending() {
		return pendingApproval;
	}
	public void setPending(boolean pending) {
		this.pendingApproval = pending;
	}
	public String getUserCpf() {
		return userCpf;
	}
	public void setUserCpf(String userCpf) {
		this.userCpf = userCpf;
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	
	
}
