package pojo;

import java.sql.Timestamp;

import dal.annotations.Column;
import dal.annotations.ForeignKey;
import dal.annotations.Storeable;

@Storeable(tableName = "Reservations")
public class Reservation {
	
	@Column(columnName = "id", autoGenerated = true, pk = true)
	public int id;
	
	@Column(columnName = "solicitation_time")
	public Timestamp solicitationTime;
	
	@Column(columnName = "start_time")
	public Timestamp startTime;
	
	@Column(columnName = "end_time")
	public Timestamp endTime;
	
	@Column(columnName = "approved")
	public boolean approved;
	
	@Column(columnName = "pending")
	public boolean pending;
	
	@Column(columnName = "userCpf")
	public String userCpf;
	@ForeignKey(thisSideAttrs = {"id"}, otherSideAttrs = {"cpf"})
	public User user;
	
	public long resourceID;
	public Resource resource;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public Timestamp getSolicitationTime() {
		return solicitationTime;
	}
	public void setSolicitationTime(Timestamp solicitationTime) {
		this.solicitationTime = solicitationTime;
	}
	public Timestamp getStartTime() {
		return startTime;
	}
	public void setStartTime(Timestamp startTime) {
		this.startTime = startTime;
	}
	public Timestamp getEndTime() {
		return endTime;
	}
	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}
	public boolean isApproved() {
		return approved;
	}
	public void setApproved(boolean approved) {
		this.approved = approved;
	}
	public boolean isPending() {
		return pending;
	}
	public void setPending(boolean pending) {
		this.pending = pending;
	}
	public String getUserCpf() {
		return userCpf;
	}
	public void setUserCpf(String userCpf) {
		this.userCpf = userCpf;
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	public long getResourceID() {
		return resourceID;
	}
	public void setResourceID(long resourceID) {
		this.resourceID = resourceID;
	}
	public Resource getResource() {
		return resource;
	}
	public void setResource(Resource resource) {
		this.resource = resource;
	}
	
	
}
