package pojo;

import dal.annotations.Column;
import dal.annotations.Storeable;

@Storeable(tableName = "Resources")
public class Resource {
	@Column(autoGenerated = true, columnName = "Resources.id", pk = true)
	public long id;
	
	@Column(columnName = "Resources.description")
	public String description;
	
	@Column(columnName = "Resources.name")
	public String name;
	
	@Column(columnName = "Resources.reservable")
	public boolean reservable;
		
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public boolean isReservable() {
		return reservable;
	}
	public void setReservable(boolean reservable) {
		this.reservable = reservable;
	}
}
