package pojo;

import java.util.List;

import dal.annotations.DBCollection;
import dal.annotations.Storeable;
import dal.annotations.Column;

@Storeable(tableName = "Sectors")
public class Sector {
	
	@Column(columnName = "id", autoGenerated = true, pk = true)
	public long id;
	
	@Column(columnName = "name")
	public String name;
	
	@Column(columnName = "description")
	public String description;
	
	@DBCollection(klass = User.class, thisPk = {"id"}, fk = {"sectorID"})
	public List<User> users;
	
	@DBCollection(klass = ObjectResource.class, thisPk = {"id"}, fk = {"sectorID"})
	public List<ObjectResource> objects;
	
	@DBCollection(klass = PlaceResource.class, thisPk = {"id"}, fk = {"sectorID"})
	public List<PlaceResource> places;

	public List<ObjectResource> getObjects() {
		return objects;
	}

	public List<PlaceResource> getPlaces() {
		return places;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<User> getUsers() {
		return users;
	}
	
	
}
